# Autogenerated by nbdev

d = { 'settings': { 'branch': 'main',
                'doc_baseurl': '/scAnnot',
                'doc_host': 'https://changebio.github.io',
                'git_url': 'https://github.com/changebio/scAnnot',
                'lib_path': 'scAnnot'},
  'syms': {'scAnnot.core': {'scAnnot.core.scAnnot': ('core.html#scannot', 'scAnnot/core.py')}}}
